apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: alertmanager
  name: storage-prometheus-alertmanager-0
  namespace: monitor
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: prometheus-storage
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
